apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../../base

namePrefix: dev-app2-

labels:
  - pairs:
      app.kubernetes.io/name: nginx-app
      app.kubernetes.io/instance: dev-app2
      app.kubernetes.io/environment: dev
      app.kubernetes.io/team: backend

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: nginx-deployment
