apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: dev-app2-config-live
    options:
      disableNameSuffixHash: true
    files:
      - config/app.properties
