apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../base

namePrefix: stage-app1-

labels:
  - pairs:
      app.kubernetes.io/name: nginx-app
      app.kubernetes.io/instance: stage-app1
      app.kubernetes.io/environment: stage
      app.kubernetes.io/team: platform

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: nginx-deployment
